use fake::Dummy;

#[derive(Debug, Dummy)]
pub enum SampleMaterialType {
    WholeBlood,
    BoneMarrow,
    BuffyCoat,
    DriedWholeBlood,
    PeripheralBloodMononuclearCells,
    Plasma,
    // PlasmaEdta,
    // PlasmaCitrat,
    // PlasmaHeparin,
    // PlasmaCellFree,
    // PlasmaOther,
    Serum,
    Ascites,
    CsfLiquor,
    Saliva,
    StoolFaeces,
    Urine,
    Swab,
    OtherLiquid,
    TissueFfpe,
    // TumorTissueFfpe,
    // NormalTissueFfpe,
    // OtherTissueFfpe,
    TissueFrozen,
    // TumorTissueFrozen,
    // NormalTissueFrozen,
    // OtherTissueFrozen,
    OtherTissueStorage,
    Dna,
    // CfDna,
    // GDna,
    Rna,
    OtherDerivative,
}

impl SampleMaterialType {
    pub fn as_str(&self) -> &'static str {
        match self {
            SampleMaterialType::WholeBlood => "whole-blood",
            SampleMaterialType::BoneMarrow => "bone-marrow",
            SampleMaterialType::BuffyCoat => "buffy-coat",
            SampleMaterialType::DriedWholeBlood => "dried-whole-blood",
            SampleMaterialType::PeripheralBloodMononuclearCells => "peripheral-blood-cells-vital",
            SampleMaterialType::Plasma => "blood-plasma",
            // SampleMaterialType::PlasmaEdta => "plasma-edta",
            // SampleMaterialType::PlasmaCitrat => "plasma-citrat",
            // SampleMaterialType::PlasmaHeparin => "plasma-heparin",
            // SampleMaterialType::PlasmaCellFree => "plasma-cell-free",
            // SampleMaterialType::PlasmaOther => "plasma-other",
            SampleMaterialType::Serum => "blood-serum",
            SampleMaterialType::Ascites => "ascites",
            SampleMaterialType::CsfLiquor => "csf-liquor",
            SampleMaterialType::Saliva => "saliva",
            SampleMaterialType::StoolFaeces => "stool-faeces",
            SampleMaterialType::Urine => "urine",
            SampleMaterialType::Swab => "swab",
            SampleMaterialType::OtherLiquid => "liquid-other",
            SampleMaterialType::TissueFfpe => "tissue-ffpe",
            // SampleMaterialType::TumorTissueFfpe => "tumor-tissue-ffpe",
            // SampleMaterialType::NormalTissueFfpe => "normal-tissue-ffpe",
            // SampleMaterialType::OtherTissueFfpe => "other-tissue-ffpe",
            SampleMaterialType::TissueFrozen => "tissue-frozen",
            // SampleMaterialType::TumorTissueFrozen => "tumor-tissue-frozen",
            // SampleMaterialType::NormalTissueFrozen => "normal-tissue-frozen",
            // SampleMaterialType::OtherTissueFrozen => "other-tissue-frozen",
            SampleMaterialType::OtherTissueStorage => "tissue-other",
            SampleMaterialType::Dna => "dna",
            // SampleMaterialType::CfDna => "cf-dna",
            // SampleMaterialType::GDna => "g-dna",
            SampleMaterialType::Rna => "rna",
            SampleMaterialType::OtherDerivative => "derivative-other",
        }
    }
}
